### ISSUE TITLE
Should this repo show up as a node server option in the polyglot 2.2.1 store

### ISSUE THREAD

**Issue by TaeKwonBow** [jimboca/udi-poly-kasa#1]

**Comment by jimboca** [comment]
It's not functional yet, I started working on it a while back but never had time get it working.  I only have a couple of the HS300 Power Strips so that was going to be my first priority, but just haven't found the time.

**Comment by TaeKwonBow** [comment]
Ok thanks.  Yeah I opened a few files and looked at them and they were really generic I figured it was a work in progress. Thanks for the other node servers you have made and I look forward to this one too once you find some time to work on it.

**Comment by jimboca** [comment]
No worries, I had planned to try and work on it this week but hadn't found the time.

**Comment by jimboca** [comment]
What devices do you have?  I have the very basics working for the HS300 SmartStrip, which is the only device I have.

**Comment by TaeKwonBow** [comment]
I've the HS300 too.

**Comment by jimboca** [comment]
Perfect, give it a try, it's in the store now but only has basic in/off capability.
