### ISSUE TITLE
Merge changes from @eagleco

### ISSUE THREAD

**Issue by jimboca** [jimboca/udi-poly-kasa#2]
Hey @eagleco do you want to submit a pull request for your changes for others to use?

**Comment by eagleco** [comment]
Sure 👍 Had been meaning to a while ago but got busy with work.  I think everything works well for smart plugs (including energy readings) except for triggering programs from the values, haven't had a chance to dig into that yet.

**Comment by jimboca** [comment]
Awesome, thank you!  I understand the busy issue... Hard to keep up with side projects.
